#!/usr/bin/env bash

___printversion(){
  
cat << 'EOB' >&2
bwp - version: 2019.08.25.4
updated: 2019-08-25 by budRich
EOB
}


# environment variables
: "${BWP_DIR:=$HOME/.cache/wallpapers}"
: "${BWP_GEOMETRY:=}"
: "${BWP_COMMAND:=feh --no-fehbg --bg-fill}"
: "${BWP_LOCK_OPTIONS:=}"
: "${BWP_LOCK_IMAGE_OPTIONS:=}"


main() {

  _wdir="$BWP_DIR/walls"
  _history="$BWP_DIR/history"

  [[ -d $_wdir ]] || {
    mkdir -p "$_wdir"
    mkdir -p "$BWP_DIR/blurs"
    ERM "BWP_DIR created at: $BWP_DIR"
  }

  # add is the only action that takes directories
  # as an argument.
  [[ -d "$*" ]] && __o[add]=1

  ((__o[add] == 1)) && {
    add_to_library "$*" > /dev/null
    exit
  }

  if [[ -n ${__o[rename]} ]] || ((__o[delete] == 1)); then
    ((__o[random]+__o[next]+__o[prev] > 0)) && ERH \
      "-r -n -p is not allowed when deleting or renaming."
  elif ! ((__o[wallpaper]+__o[blur]+__o[lock] > 0)); then
    # if no action is specified, defualt to wallpaper
    __o[wallpaper]=1
  fi

  _curpth="$(readlink "$BWP_DIR/currentwall")"
  _curnam="${_curpth##*/}"
  
  _wall="$(get_wall "$@")"

  if   ((__o[delete] == 1)); then
    delete_wall "$_wall"
  elif [[ -n ${__o[rename]} ]]; then
    rename_wall "${__o[rename]}" "$_wall"
  elif ((__o[lock] ==1)); then
    set_lock "$_wall"
  elif ((__o[wallpaper] == 1)) || ((__o[blur] == 1)); then
    set_wall "$_wall"
  fi


}

___printhelp(){
  
cat << 'EOB' >&2
bwp - budlabs wallpaper selector


SYNOPSIS
--------
bwp [--prev|-p|--next|-n|--random|-r|WALLPAPER]
bwp --blur|-b [--prev|-p|--next|-n|--random|-r|WALLPAPER|DIR]     
bwp --lock|-l [--lock-options|-L OPTIONS] [--image-options|-I OPTIONS] [--wallpaper|-w|--random|-r|WALLPAPER]     
bwp --delete|-d [--force|-f] [WALLPAPER]                      
bwp --add|-a    [--force|-f] FILE|DIR                           
bwp --rename|-x NEWNAME [WALLPAPER]                           
bwp --help|-h                                                 
bwp --version|-v                                              

OPTIONS
-------

--prev|-p  
takes the previous wallpaper according to
BWP_DIR/history


--next|-n  
takes the next wallpaper according to
BWP_DIR/history


--random|-r  
get a random wallpaper from BWP_DIR/walls


--blur|-b  
toggle/set blur. If no WALLPAPER is specified the
blur state of the current wallpaper will get
toggled.


--lock|-l  
locks the computer with i3lock(1). If no
WALLPAPER is specified, the last image that was
last used as lockscreen background will be used.


--lock-options|-L OPTIONS  
Additional command line options passed to i3lock.
If OPTIONS is the path to a file, the content of
that file will be used. This options overrides the
environment variable: BWP_LOCK_OPTIONS


--image-options|-I OPTIONS  
Additional command line options passed to convert
before locking the screen. If OPTIONS is the path
to a file, the content of that file will be used.
This options overrides the environment variable:
BWP_LOCK_IMAGE_OPTIONS


--wallpaper|-w  
when set in conjunction with --lock, the current
wallpaper will be used as lockscreen background.


--delete|-d  
delete WALLPAPER from library and history. Use
--force option to skip prompt.


--force|-f  
if set --delete option will not prompt and when
adding files to the library (--add) existing files
with the same name will get overwritten.


--add|-a  
if a argument is a FILE it will get added to the
library. If argument is a DIRECTORY all images in
that directory will get added to the library. Use
--force option to overwrite existing files.


--rename|-x NEWNAME  
rename WALLPAPER to NEWNAME


--help|-h  
Show help and exit.


--version|-v  
Show version and exit.
EOB
}


add_to_history() {
  local name

  name="$1"

  if [[ -f $_history ]]; then
  
    awk -v name="$name" '
      BEGIN {a[name]=1 ; print name}
      !a[$0]++
    ' "${_history:-}" > /tmp/bwphist

    cat /tmp/bwphist > "$_history"
  else
    echo "$name" > "$_history"
  fi
}

add_to_library() {

  local src trg name

  src="$1"

  ((__o[delete] == 1)) \
    && ERX "file path not a valid arg to delete action"

  if [[ -d "$src" ]]; then
    find "$src"  -iregex '.*\.\(jpg\|png\)' -print0 | {
      if command -v parallel > /dev/null; then
        parallel -0 --bar "BWP_GEOMETRY=$(get_geometry) \
          bwp -a ${__o[force]:+-f}" "{}" :::: -
      else
        xargs -0 -i{} BWP_GEOMETRY="$(get_geometry)" \
          bwp -a ${__o[force]:+-f} "{}"
      fi
    }
    exit
  elif [[ ! -f $src ]]; then
    ERX "'$src' is not a file."
  fi

  : "${BWP_GEOMETRY:=$(get_geometry)}"

  mapfile imageinfo < <(identify -format '%m\n%wx%h' "$src")

  [[ ${imageinfo[0]:-} =~ PNG|JPEG ]] \
    || ERX "'$src' is not an image."

  trg="$_wdir/${src##*/}" trg="${trg%.*}"
  name="${trg##*/}"

  if [[ -f $trg ]] && ((__o[force] != 1)); then
    ERR "$trg already exist in library"
  else
    # resize image
    if [[ ${imageinfo[1]} = "${BWP_GEOMETRY}" ]]; then
      cp -f "$src" "$trg"
    else
      convert "$src"                 \
        -resize  "${BWP_GEOMETRY}^"  \
        -gravity center              \
        -extent  "${BWP_GEOMETRY}"   \
        "$trg"
    fi

    ((__o[wallpaper] == 1)) \
      && set_wall "$name" && __o[wallpaper]=0
      
    generate_blur "$trg" "${trg/walls/blurs}" "${imageinfo[0]:-}"
    
  fi

  echo "$name"
}

delete_wall() {
  local trg

  trg="$1"

  ((__o[delete] == 1)) && ((__o[force] != 1)) && {
    YNP -n "delete $trg?" || ERX "deletion aborted"
  }
  
  rm "$BWP_DIR"/*/"$trg"
  sed -i "/^${trg}$/d" "$_history"

  [[ $trg = "$_curnam" ]] && {
    set_wall "$(get_previous_wall)"
  }
}

set -E
trap '[ "$?" -ne 77 ] || exit 77' ERR

ERM(){ >&2 echo "$*"; }
ERR(){ >&2 echo "[WARNING]" "$*"; }
ERX(){ >&2 echo "[ERROR]" "$*" && exit 77 ; }
ERH(){
  {
    ___printhelp 
    [[ -n "$*" ]] && printf '\n%s\n' "$*"
  } >&2 
  exit 77
}

generate_blur() {
  local src trg ext

  src="$1" trg="$2" ext="$3"

  convert "$src"                     \
          -blur 0x8                  \
          -set "png:format" png32    \
          -quality 85                \
          "$trg"

  # if pngquant is installed it will be used to 
  # convert png32 to png8 saving us some diskspace
  [[ $ext =~ PNG ]] && command -v pngquant > /dev/null && {
    pngquant -fo "${trg}.png" "$trg" \
      &&  mv -f  "${trg}.png" "$trg"
  }
}

get_blur() {
  local name bdir

  name="$1"
  bdir="$BWP_DIR/blurs"

  if [[ "$_curpth" = "$bdir/$name" ]]; then
    echo "$_wdir/$name"
  else 
    
    [[ -f "$bdir/$name" ]] \
      || generate_blur "$_wdir/$name" "$bdir/$name"

    echo "$bdir/$name"
  fi
}

get_geometry() {
  echo "${BWP_GEOMETRY:=$(xrandr | awk '/[*]/ {print $1; exit}')}"
}


get_next_wall() {
  local trg firstline

  if [[ -f "$_history" ]]; then
    firstline="$(head -1 "$_history")"

    if [[ $firstline = "$_curnam" ]]; then
      get_random_wall
    else
      trg="$(awk -v current="$_curnam" '
        $0 == current {print lastline ; exit}
        {lastline = $0}
      ' "$_history")"

      if [[ -z $trg ]]; then
        rm "$_history"
        ERX "history is empty"
      elif [[ -f "$_wdir/$trg" ]]; then
        echo "$trg"
      else
        delete_wall "$trg"
        get_next_wall 
      fi
    fi
  else
    get_random_wall
  fi
}

get_previous_wall() {
  if [[ -f "$_history" ]]; then
    trg="$(awk -v current="$_curnam" '
      NR == 1       {firstline = $0}
      foundit == 1  {found = $0 ; exit}
      $0 == current {foundit = 1}

      END {
        if (found)
          print found
        else
          print firstline
      }
    ' "$_history")"

    if [[ -z $trg ]]; then
      ERX "history is empty"
    elif [[ -f "$_wdir/$trg" ]]; then
      echo "$trg"
    else
      delete_wall "$trg"
      get_previous_wall 
    fi
  else
    echo "$_curnam"
  fi
}

get_random_wall() {

  local rnd

  rnd="$(
    find "${_wdir}"        \
      ! -path "${_wdir}"   \
      ! -name "${_curnam}" \
      -printf '%f\n' \
    | sort -R | head -1
  )"

  ((__o[next] == 1)) && add_to_history "${rnd:=$_curnam}"
  echo "$rnd"
}

get_wall() {
  if ((__o[random] == 1)); then
    get_random_wall
  elif ((__o[prev] == 1)); then
    get_previous_wall
  elif ((__o[next] == 1)); then
    get_next_wall
  elif [[ -z $1 ]]; then
    
    if ((__o[lock]+__o[wallpaper] == 2)) && [[ -f "$BWP_DIR/currentwall" ]]; then
      echo "$_curnam"
    elif ((__o[lock] == 1)) && [[ -f "$BWP_DIR/currentlock" ]]; then
      basename "$(readlink "$BWP_DIR/currentlock")"
    elif ((__o[lock] != 1)) && [[ -f "$BWP_DIR/currentwall" ]]; then
      echo "$_curnam"
    else
      get_random_wall
    fi
  elif [[ -f "$*" ]]; then
    add_to_library "$*"
  elif [[ -f "$_wdir/$*" ]]; then
    echo "$*"
  else
    ERX "Not a valid argument '$*'"
  fi
}

rename_wall() {
  local newname trg f

  newname="$1"
  trg="$2"

  for f in "$BWP_DIR"/*/"$trg" ; do
    mv -f "$f" "${f%/*}/$newname"
  done

  [[ -f "$_history" ]] \
    && sed -i "s/^${trg}$/${newname}/" "$_history"

  [[ $trg = "$_curnam" ]] \
    && ln -fs "${f%/*}/$newname" "$BWP_DIR/currentwall"
}

set_lock() {

  local trg screenArea io lo

  trg="$BWP_DIR/walls/$1"

  io="${__o[image-options]:-${BWP_LOCK_IMAGE_OPTIONS:-}}"
  lo="${__o[lock-options]:-${BWP_LOCK_OPTIONS:-}}"

  [[ -f "$io" ]] && io="$(cat "$io")"
  [[ -f "$lo" ]] && lo="$(cat "$lo")"

  mapfile -t screens < <(xrandr | awk '
    
    # get screen area
    match($0,/.*current\s([0-9]+.*[0-9]+),.*/,ma) {
      print gensub(/ /,"","g",ma[1])
    }

    # connected screens
    / connected/ && /mm$/ {
      if ($3 == "primary")
        primary=$4
      else s[$1]=$3
    } 

    END {
      # print the primary screen first
      print primary
      for (m in s) {print s[m]}
    }
  ')

  screenArea="${screens[0]}"
  unset 'screens[0]'

  # if multiple screens are active stretch blurred
  # version of image
  if ((${#screens[@]} > 1)); then
    io="                             \
      ${trg/walls/blurs}             \
      -gravity Center                \
      -resize '${screenArea}^'       \
      -extent '${screenArea}'        \
      \(                             \
        '$trg'                       \
        -gravity Center              \
        -extent '${screens[1]%%+*}'  \
      \)                             \
      -gravity NorthWest             \
      -geometry '+${screens[1]#*+}'  \
      -composite                     \
      $io"
  else
    io="${trg} ${io}"
  fi

  eval i3lock                                     \
    --raw   "$screenArea":rgb                     \
    --image <(eval convert                        \
                     "${io}"                      \
                     -set png:format png32 RGB:-) \
    "${lo}"                                       \

  ln -fs "$trg" "$BWP_DIR/currentlock"
}


set_wall(){
  local name trg

  name="$1"
  trg="${_wdir}/$name"

  if [[ -z $name ]] || [[ ! -f $trg ]]; then
    ERX "no such wallpaper"
  else
    command -v "${BWP_COMMAND%% *}" > /dev/null \
      || ERX "BWP_COMMAND '$BWP_COMMAND' not found"
      
    ((__o[blur] == 1)) && trg="$(get_blur "$name")"

    ${BWP_COMMAND} "$trg"

    ln -fsn "$trg" "$BWP_DIR/currentwall"

    ((__o[prev]+__o[next] > 0)) || add_to_history "$name"
  fi
}

YNP() {

  local sp key default opts status

  default=y
  opts=yn

  [[ $1 =~ -([${opts}]) ]] \
    && default="${BASH_REMATCH[1]}" && shift

  sp="$* [${default^^}/${opts/$default/}]"

  if [[ -t 2 ]]; then
    >&2 echo "$sp"

    while :; do
      read -rsn 1

      key="${REPLY:-$default}"
      [[ $key =~ [${opts}] ]] || continue
      break
    done
  else
    key="$default"
  fi

  [[ ${key,,} = n ]] && status=1

  return "${status:-0}"
}

declare -A __o
eval set -- "$(getopt --name "bwp" \
  --options "pnrblL:I:wdfax:hv" \
  --longoptions "prev,next,random,blur,lock,lock-options:,image-options:,wallpaper,delete,force,add,rename:,help,version," \
  -- "$@"
)"

while true; do
  case "$1" in
    --prev       | -p ) __o[prev]=1 ;; 
    --next       | -n ) __o[next]=1 ;; 
    --random     | -r ) __o[random]=1 ;; 
    --blur       | -b ) __o[blur]=1 ;; 
    --lock       | -l ) __o[lock]=1 ;; 
    --lock-options | -L ) __o[lock-options]="${2:-}" ; shift ;;
    --image-options | -I ) __o[image-options]="${2:-}" ; shift ;;
    --wallpaper  | -w ) __o[wallpaper]=1 ;; 
    --delete     | -d ) __o[delete]=1 ;; 
    --force      | -f ) __o[force]=1 ;; 
    --add        | -a ) __o[add]=1 ;; 
    --rename     | -x ) __o[rename]="${2:-}" ; shift ;;
    --help       | -h ) ___printhelp && exit ;;
    --version    | -v ) ___printversion && exit ;;
    -- ) shift ; break ;;
    *  ) break ;;
  esac
  shift
done

[[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
  && __lastarg="" 


main "${@:-}"


