.TH BWP 1 2019\-08\-09 Linux "User Manuals"
.SH NAME
.PP
\fB\fCbwp\fR \- SHORT DESCRIPTION

.SH SYNOPSIS
.PP
.RS

.nf
bwp \-\-wallpaper|\-w [\-\-prev|\-p|\-\-next|\-n|\-\-random|\-r|**WALLPAPER**]
bwp \-\-blur|\-b [\-\-prev|\-p|\-\-next|\-n|\-\-random|\-r|**WALLPAPER**]     
bwp \-\-lock|\-l [\-\-prev|\-p|\-\-next|\-n|\-\-random|\-r|**WALLPAPER**]     
bwp \-\-delete|\-d [\-\-force|\-f] [**WALLPAPER**]                      
bwp \-\-add|\-a [\-\-force|\-f] **FILE|DIR**                           
bwp \-\-rename|\-x NEWNAME [**WALLPAPER**]                           
bwp \-\-help|\-h                                                 
bwp \-\-version|\-v                                              

.fi
.RE

.SH DESCRIPTION
.PP
LONG DESCRIPTION

.SH OPTIONS
.PP
\fB\fC\-\-wallpaper\fR|\fB\fC\-w\fR
.br
set desktop wallpaper

.PP
\fB\fC\-\-prev\fR|\fB\fC\-p\fR
.br
takes the previous wallpaper according to
BWP\_DIR/history

.PP
\fB\fC\-\-next\fR|\fB\fC\-n\fR
.br
takes the next wallpaper according to
BWP\_DIR/history

.PP
\fB\fC\-\-random\fR|\fB\fC\-r\fR
.br
get a random wallpaper from BWP\_DIR/walls

.PP
\fB\fC\-\-blur\fR|\fB\fC\-b\fR
.br
toggle/set blur

.PP
\fB\fC\-\-lock\fR|\fB\fC\-l\fR
.br
lock screen

.PP
\fB\fC\-\-delete\fR|\fB\fC\-d\fR
.br
delete wallpaper from library

.PP
\fB\fC\-\-force\fR|\fB\fC\-f\fR
.br
if set \fB\fC\-\-delete\fR option will not prompt and when
adding files to the library (\fB\fC\-\-add\fR) existing
files with the same name will get overwritten.

.PP
\fB\fC\-\-add\fR|\fB\fC\-a\fR
.br
add a new image to the library

.PP
\fB\fC\-\-rename\fR|\fB\fC\-x\fR NEWNAME
.br
rename WALLPAPER to NEWNAME

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit. whatever newline. this is
also a new line.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCBWP\_DIR\fR
.br
amani[environ][0][BWP\_DIR][description] defaults
to: $HOME/tmp/bwp

.PP
\fB\fCBWP\_GEOMETRY\fR
.br
amani[environ][1][BWP\_GEOMETRY][description]
defaults to: \-

.PP
\fB\fCBWP\_COMMAND\fR
.br
amani[environ][2][BWP\_COMMAND][description]
defaults to: feh \-\-no\-fehbg \-\-bg\-fill

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCsed\fR

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), sed(1),
