.TH BWP 1 2019\-08\-25 Linux "User Manuals"
.SH NAME
.PP
\fB\fCbwp\fR \- budlabs wallpaper selector

.SH SYNOPSIS
.PP
.RS

.nf
bwp [\-\-prev|\-p|\-\-next|\-n|\-\-random|\-r|WALLPAPER]
bwp \-\-blur|\-b [\-\-prev|\-p|\-\-next|\-n|\-\-random|\-r|WALLPAPER|DIR]     
bwp \-\-lock|\-l [\-\-lock\-options|\-L OPTIONS] [\-\-image\-options|\-I OPTIONS] [\-\-wallpaper|\-w|\-\-random|\-r|WALLPAPER]     
bwp \-\-delete|\-d [\-\-force|\-f] [WALLPAPER]                      
bwp \-\-add|\-a    [\-\-force|\-f] FILE|DIR                           
bwp \-\-rename|\-x NEWNAME [WALLPAPER]                           
bwp \-\-help|\-h                                                 
bwp \-\-version|\-v                                              

.fi
.RE

.SH DESCRIPTION
.PP
The argument WALLPAPER is available for all
actions except \fB\fC\-\-add\fR and can be either the name
of a file in \fB\fCBWP\_DIR/walls\fR or the path to a file
(\fIif the file doesn't exist in the library, it
will get added before the action is applied\fP). If
the WALLPAPER argument is omitted and no navigate
action (\fB\fC\-\-next\fR,\fB\fC\-\-pre\fR,\fB\fC\-\-random\fR) is specified
the action will get applied to the \fBcurrentwall\fP
(\fIthe file that \fB\fCBWP\_DIR/currentwall\fR links
to.*\fP)

.PP
*(*except for the \fB\fC\-\-lock\fR action that will use
\fB\fCBWP\_DIR/currentlock\fR\&. To set the lockscreen to
the \fBcurrentwall\fP, use the \fB\fC\-\-wallpaper\fR
option*).

.SH OPTIONS
.PP
\fB\fC\-\-prev\fR|\fB\fC\-p\fR
.br
takes the previous wallpaper according to
BWP\_DIR/history

.PP
\fB\fC\-\-next\fR|\fB\fC\-n\fR
.br
takes the next wallpaper according to
BWP\_DIR/history

.PP
\fB\fC\-\-random\fR|\fB\fC\-r\fR
.br
get a random wallpaper from BWP\_DIR/walls

.PP
\fB\fC\-\-blur\fR|\fB\fC\-b\fR
.br
toggle/set blur. If no WALLPAPER is specified the
blur state of the current wallpaper will get
toggled.

.PP
\fB\fC\-\-lock\fR|\fB\fC\-l\fR
.br
locks the computer with \fB\fCi3lock(1)\fR\&. If no
WALLPAPER is specified, the last image that was
last used as lockscreen background will be used.

.PP
\fB\fC\-\-lock\-options\fR|\fB\fC\-L\fR OPTIONS
.br
Additional command line options passed to
\fB\fCi3lock\fR\&. If OPTIONS is the path to a file, the
content of that file will be used. This options
overrides the environment variable:
\fB\fCBWP\_LOCK\_OPTIONS\fR

.PP
\fB\fC\-\-image\-options\fR|\fB\fC\-I\fR OPTIONS
.br
Additional command line options passed to
\fB\fCconvert\fR before locking the screen. If OPTIONS is
the path to a file, the content of that file will
be used. This options overrides the environment
variable: \fB\fCBWP\_LOCK\_IMAGE\_OPTIONS\fR

.PP
\fB\fC\-\-wallpaper\fR|\fB\fC\-w\fR
.br
when set in conjunction with \fB\fC\-\-lock\fR, the
current wallpaper will be used as lockscreen
background.

.PP
\fB\fC\-\-delete\fR|\fB\fC\-d\fR
.br
delete WALLPAPER from library and history. Use
\fB\fC\-\-force\fR option to skip prompt.

.PP
\fB\fC\-\-force\fR|\fB\fC\-f\fR
.br
if set \fB\fC\-\-delete\fR option will not prompt and when
adding files to the library (\fB\fC\-\-add\fR) existing
files with the same name will get overwritten.

.PP
\fB\fC\-\-add\fR|\fB\fC\-a\fR
.br
if a argument is a FILE it will get added to the
library. If argument is a DIRECTORY all images in
that directory will get added to the library. Use
\fB\fC\-\-force\fR option to overwrite existing files.

.PP
\fB\fC\-\-rename\fR|\fB\fC\-x\fR NEWNAME
.br
rename WALLPAPER to NEWNAME

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCBWP\_DIR\fR
.br
Directory where wallpapers and history file will
get stored. defaults to: $HOME/.cache/wallpapers

.PP
\fB\fCBWP\_GEOMETRY\fR
.br
($WIDTHx$HEIGHT) if set, images added to the
library will be resized (if needed) to the
dimensions specified. If not set, images will be
resized (if needed) to the same dimensions as the
currently active monitor. defaults to:

.PP
\fB\fCBWP\_COMMAND\fR
.br
Command used to set the wallpaper. defaults to:
feh \-\-no\-fehbg \-\-bg\-fill

.PP
\fB\fCBWP\_LOCK\_OPTIONS\fR
.br
Additional command line options passed to
\fB\fCi3lock\fR\&. \fB\fC\-\-lock\-options\fR will override this
variable if set. defaults to:

.PP
\fB\fCBWP\_LOCK\_IMAGE\_OPTIONS\fR
.br
Additional command line options passed to
\fB\fCconvert\fR before locking the screen.
\fB\fC\-\-image\-options\fR will override this variable if
set. defaults to:

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCsed\fR \fB\fCImageMagick\fR \fB\fCi3lock\fR

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
i3lock(1), ImageMagick(1), parallel(1), pngquant(1),
