.TH BWPDEV 1 2019\-08\-09 Linux "User Manuals"
.SH NAME
.PP
\fB\fCbwpdev\fR \- SHORT DESCRIPTION

.SH SYNOPSIS
.PP
.RS

.nf
bwpdev \-\-help|\-h
bwpdev \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
LONG DESCRIPTION

.SH OPTIONS
.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
\fB\fCBASHBUD\_DIR\fR
.br
bashbud config dir location. defaults to:
$XDG\_CONFIG\_HOME/bashbud

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCsed\fR

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), sed(1),
